# Generated by Django 3.2.9 on 2021-12-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCE_Proj', '0002_auto_20211129_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='nickname',
            field=models.CharField(default='', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='role',
            field=models.CharField(default='registered', max_length=10, null=True),
        ),
    ]
