# Generated by Django 3.2.9 on 2021-12-05 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SCE_Proj', '0003_auto_20211204_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
