# Generated by Django 3.2.9 on 2022-01-06 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCE_Proj', '0010_auto_20220106_0738'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
